// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHvHPW-qMaZR3b0od_ip7zyv0p5E9cMis',
    appId: '1:718588495573:web:937fbbdacb7455661dc45c',
    messagingSenderId: '718588495573',
    projectId: 'proyecto-flutter-316b1',
    authDomain: 'proyecto-flutter-316b1.firebaseapp.com',
    databaseURL: 'https://proyecto-flutter-316b1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'proyecto-flutter-316b1.firebasestorage.app',
    measurementId: 'G-V52BZFXT22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx_ZUMMz4-5XkE8d73k29D1LCqErInwqU',
    appId: '1:718588495573:android:70a04b756ca50ad21dc45c',
    messagingSenderId: '718588495573',
    projectId: 'proyecto-flutter-316b1',
    databaseURL: 'https://proyecto-flutter-316b1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'proyecto-flutter-316b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALDUw-oibday5wmyZs75Qf2aakn6zNZBw',
    appId: '1:718588495573:ios:28d06e17ad45d8381dc45c',
    messagingSenderId: '718588495573',
    projectId: 'proyecto-flutter-316b1',
    databaseURL: 'https://proyecto-flutter-316b1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'proyecto-flutter-316b1.firebasestorage.app',
    iosBundleId: 'com.example.flutterProyectoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALDUw-oibday5wmyZs75Qf2aakn6zNZBw',
    appId: '1:718588495573:ios:28d06e17ad45d8381dc45c',
    messagingSenderId: '718588495573',
    projectId: 'proyecto-flutter-316b1',
    databaseURL: 'https://proyecto-flutter-316b1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'proyecto-flutter-316b1.firebasestorage.app',
    iosBundleId: 'com.example.flutterProyectoFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHvHPW-qMaZR3b0od_ip7zyv0p5E9cMis',
    appId: '1:718588495573:web:ba222b455f858e9b1dc45c',
    messagingSenderId: '718588495573',
    projectId: 'proyecto-flutter-316b1',
    authDomain: 'proyecto-flutter-316b1.firebaseapp.com',
    databaseURL: 'https://proyecto-flutter-316b1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'proyecto-flutter-316b1.firebasestorage.app',
    measurementId: 'G-428PWP4GWW',
  );

}